### ISSUE TITLE
Gdańsk

### ISSUE THREAD

**Issue by KrzysztofMadejski** [gakowalski/foss-in-gov-pl#1]
Jeżeli samorządy też się w to łapią to do listy można by dodać Bank Nasadzeń Drzew zrealizowany na zamówienie Miasta Gdańsk: http://kodujdlapolski.pl/projects/band-bank-nasadzen-drzew/

https://kodujdlapolski.pl/projects/wyrzuc-to/ też było częściowo zamawiane przez Gdańsk (panel zarządzający dla Zarządu Utylizacji), ale ownership jest w tym projekcie dość rozmyty.

**Comment by gakowalski** [comment]
Dziękuję za info, dopisałem te projekty do listy pod pozycją "Miasto Gdańsk". Dodałem linki bezpośrednio do repozytoriów a nie wpisywałem tych do stron projektów w serwisie Koduj dla Polski, aby nie prowadzić ludzi na około i nie mnożyć bytów, ale jeżeli chciałbyś, aby te linki się tam jednak znalazły to zaproponuj zmianę pull requestem.
